[package]
name = "madonox/commons"
version = "0.1.2"
registry = "https://github.com/UpliftGames/wally-index"
description = "Commons is a utility module that aims to provide a variety of useful tools for Roblox developers."
realm = "shared"
license = "MIT"
authors = ["Madonox"]
exclude = ["tests"]

[dependencies]
